name: CI

on: [push]

jobs:
  sast_scan_Bandit:
    name: SAST - Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json
          

  dast_scan_zap:
    name: DAST - ZAP Scan
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
  
    - name: Install dependencies
      run: pip install -r requirements.txt
  
    - name: Run dev Server
      run: |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000 &
  
    - name: Run ZAP Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        target: 'http://localhost:8000'  
        cmd_options: '-a -J zap-report.json'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: zap-findings
        path: zap-report.json

          
  image_scan:
   name: Docker Image Security Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout Source Code
     uses: actions/checkout@v4

   - name: Set up Docker
     uses: docker/setup-buildx-action@v3.8.0
     
   - name: Build Docker Image
     run: docker build -f Dockerfile -t pygoat-app:latest .
    
   - name: Docker Scout Scan
     uses: docker/scout-action@v1.16.1
     with:
       dockerhub-user: ${{ secrets.REPO_USER }}
       dockerhub-password: ${{ secrets.REPO_PWD }}
       command: quickview,cves
       only-severities: critical,high
       sarif-file: scout-report.sarif

   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: docker-scout-findings
       path: scout-report.sarif

